-- BACKFILL (no-op): documents a migration recorded live as version
-- 20260925182609 / reports_one_open_per_target. The real, committed content for this migration
-- lives at supabase/migrations/20260925050000_reports_one_open_per_target.sql — that file was committed
-- under a cleaned-up/rounded timestamp that doesn't match the exact
-- version Postgres recorded at apply time. Per this repo's rule against
-- editing or renaming an already-run migration file, that file is left
-- as-is; this stub exists only so the local migrations directory has an
-- exact match for every version in supabase_migrations.schema_migrations,
-- which the "Supabase Preview" CI check verifies.
--
-- This file intentionally applies nothing.
