-- NoSpace: post-signup onboarding v2 — a Space picker + optional first
-- Moments, gated by a real /onboarding route instead of the old inline
-- 3-step setup on /you (name/photo/tagline/free-text interests, gated by
-- profiles.onboarding_completed_at). That flow is retired by this change
-- (ProfileOnboarding.tsx and lib/onboardingLocal.ts are deleted from the
-- app); onboarding_completed_at and tagline are left in the schema as-is —
-- existing data in them is harmless, and tagline is still a real,
-- independently-editable profile field, just with no dedicated edit surface
-- left after this until a future pass adds one.
--
--   Supabase → SQL Editor → New query → paste → Run
--
-- Safe to re-run.
--
-- Every CURRENTLY existing row is backfilled to true in the same
-- statement that adds the column — this is a gate for brand-new signups
-- going forward, not something to retroactively force on every account
-- that already exists (including ones that finished, skipped, or predate
-- the old onboarding entirely). Only a profile row inserted *after* this
-- migration gets the fresh `false` default and actually sees /onboarding.
alter table public.profiles add column if not exists onboarding_completed boolean not null default false;
update public.profiles set onboarding_completed = true where onboarding_completed = false;
